### ISSUE TITLE
Auto-sync

### ISSUE THREAD

**Issue by understorey** [retorquere/zotero-folder-import#28]
Is there a way to set auto-sync to a folder in a way that only adds the new files to the Zotero library?
Also, that identifies that you moved a pdf to a different folder.

**Comment by retorquere** [comment]
If you go into Zotero's [hidden preferences](https://www.zotero.org/support/preferences/hidden_preferences) you can find a setting named `rmlint`; if you install [rmlint](https://rmlint.readthedocs.io/en/latest/) and add the full path in that hidden setting, the extension will use rmlint to detect duplicates and will not import those duplicates.
