### ISSUE TITLE
Add-on not working in 6.0.9

### ISSUE THREAD

**Issue by alohacocoa** [retorquere/zotero-folder-import#29]
This add-on has saved a me a lot of time in the past so first of all let me say thank you to the creators!

Unfortunately, it seems no longer functional in 6.0.9, which is the version I am on. I can't say for certain from which version it stopped working as it's been a while since I used Zotero.

**Comment by retorquere** [comment]
Sorry I missed this. Is this still the case?

**Comment by inomoz** [comment]
Same issue. On 6.0.20 version extension (0.0.5) working,  but adding only pdf files. 

In import dialog I still see options to add other files types, but app not adding them (I tried different combinations).

**Comment by dinya** [comment]
> Same issue. On Zotero 6.0.20, extension v. 0.0.5 working, but adding only pdf files. I use linking to files.
> 
> In import dialog I still see options to add other files types, but Zotero not adding them (I tried different combinations).

The same on 6.0.22: adding pdf only.

**Comment by retorquere** [comment]
@dinya can upgrade to the latest release and try again?

**Comment by Inom-Turdikulov** [comment]
For me nothing changed, still adding only pdf from directory.
```
~/Downloads/samples
ls
file_example_JPG_100kB.jpg  sample2.djvu  sample.pdf
```
![image](https://user-images.githubusercontent.com/3938577/224636922-86d4846d-e218-4a00-807c-118b29432d73.png)
![image](https://user-images.githubusercontent.com/3938577/224637411-cc9cee87-cc2a-4022-869e-64b890b76a08.png)

**Comment by dinya** [comment]
@retorquere 

> can you upgrade to the latest release and try again?

No changes -- still pdf import only ("Store copy of files", lastest Zotero 6.0.23 under Windows 10 x64).

**Comment by retorquere** [comment]
Can you:

* install build 34 just posted above
* go into Help - Debug output logging - restart
* reproduce the problem (open the prefs window)
* Go to Help - Send debug log to file.io

You will get a popup with an alphanumeric string, please post that here.

**Comment by Inom-Turdikulov** [comment]
`OQhSwJO8NQOk-UFDSI73Q` @retorquere

**Comment by retorquere** [comment]
Can you try build 35%

**Comment by Inom-Turdikulov** [comment]
> Can you try build 35?

Yes. I just tried and it's working correctly (both linking and attaching files)! Thank you for your plugin and hard work. It's making my workflow with Zotero better 🙂.
