### ISSUE TITLE
Add Bookmarks index for imported PDFs

### ISSUE THREAD

**Issue by sancho-s** [retorquere/zotero-folder-import#31]
For a Zotero item, whenever I add a pdf file in disk (either the file or a link to it), the tag structure of the pdf is read, and it is shown as an hyperlinked table of contents, so clicking on it opens the pdf at the location of the item.

But when I add Zotero items via [zotero-folder-import], the table of contents is not added.
Can this be done?

Thanks!

**Comment by retorquere** [comment]
I don't know this functionality. Where does this table of contents show up?

**Comment by sancho-s** [comment]
In Zotero, if you select an item, expand its attachments, and select a pdf attachment that was added via "Attach link to file", in the right hand panel you will see:
* The name of the file
* Filename: <filename> (yes, again!)
* Modified: <dale-time>
* Indexed: <status>
And if the table of contents exists, it will show right below this. 
Of course, the original pdf has to have that. 
I am not sure which are all possible ways to obtain this table.

**Comment by retorquere** [comment]
Do you have a sample pdf known to trigger the desired behavior?

**Comment by sancho-s** [comment]
Yes, I am attaching it here.
[Buckling.pdf](https://github.com/retorquere/zotero-folder-import/files/11016804/Buckling.pdf)

PS: There is a related [thread](https://forums.zotero.org/discussion/103765/import-pdf-as-shortcut#latest) in Zotero forum.
[Buckling.pdf](https://github.com/retorquere/zotero-folder-import/files/11016804/Buckling.pdf)

**Comment by retorquere** [comment]
According to that thread, the TOC thing is a Zotfile feature, so you would have to ask there why it isn't being generated. folder-import is calling the same functions that Zotero itself calls when importing/linking attachments.

**Comment by sancho-s** [comment]
What I mean is that, apparently, Zotero has two different ways of attaching a PDF, and they perform differently:
1. Via Ctrl+Shift+drag of the PDF into the Zotero item.
2. Via menus and "Attach link to file". This creates the table of contents.

Perhaps [zotero-folder-import] can be instructed to work like #2.

I don't know about the interaction Zotero-Zotfile, and I am not even sure extraction of the table of contents is done by Zotfile or Zotero itself.
For instance, [apparently](https://guides.lib.berkeley.edu/zotero/zotfile), since Zotero 6.0, extraction of annotations is not done by Zotfile anymore, but by Zotero.

**Comment by retorquere** [comment]
If adamsmith says that this is done by Zotfile I'm inclined to believe him. Can you first go check whether @jlegewie agrees with adamsmith before I dive into the Zotero code? If it's Zotfile's feature to do this I'll be glad to help where needed, but would prefer to keep @jlegewie in the lead for it. If it is indeed not a Zotfile feature but something Zotero does itself, that would be a different matter.

**Comment by retorquere** [comment]
What is zotero's behavior if you don't have Zotfile installed?

**Comment by retorquere** [comment]
> What I can reproduce is that adding via [zotero-folder-import] does not get the table of contents. Which, on a file-by-file basis, can be fixed via Select the PDF item -> Right click -> Manage Attachments -> Get table of contents.
> 
> Summarizing, it seems that now [zotero-folder-import] does not do exactly the same a Zotfile... which is very strange.

As soon as @jlewegie weighs in, I can see what to do about this (or whether there is anything to do). I do not know what initiates this behavior, and adamsmith, who is deeply involved with Zotero, says it is Zotfile doing this.

**Comment by retorquere** [comment]
not heard from jlewegie since

**Comment by jlegewie** [comment]
This was a zotfile feature that received very little attention. I am not sure whether zotero ever integrated it but I don't think so. I think the main implementation is here (with no updates for 8 years): https://github.com/jlegewie/zotfile/blob/master/chrome/content/zotfile/pdfextract/toc.js

**Comment by retorquere** [comment]
This sounds like something than could be done usings tags & actions, at least for the interim. Still backed up with a lot of existing plugin work.
