### ISSUE TITLE
Select all file types on import

### ISSUE THREAD

**Issue by dinya** [retorquere/zotero-folder-import#32]
Currently the plugin asks the selection of file types "checkbox by checkbox".

But if there are a lot of checkboxes and the user wants to mark them all, it will be hard work for the finger.

![](https://user-images.githubusercontent.com/2182222/226266744-d75505bf-e602-48b2-a289-3299c07bea11.png)

It would be pretty cool if "Select all"/"Deselect all" buttons were added.

**Comment by retorquere** [comment]
superseded by #39
