### ISSUE TITLE
> What I can reproduce is that adding via [zotero-folder-import] does not get the table of contents. Which, on a file-by-file basis, can be fixed via Select the PDF item -> Right click -> Manage Attachments -> Get table of contents.

### ISSUE THREAD

**Issue by BellaZq** [retorquere/zotero-folder-import#35]
> What I can reproduce is that adding via [zotero-folder-import] does not get the table of contents. Which, on a file-by-file basis, can be fixed via Select the PDF item -> Right click -> Manage Attachments -> Get table of contents.
> 
> Summarizing, it seems that now [zotero-folder-import] does not do exactly the same a Zotfile... which is very strange.

As soon as @jlewegie weighs in, I can see what to do about this (or whether there is anything to do). I do not know what initiates this behavior, and adamsmith, who is deeply involved with Zotero, says it is Zotfile doing this.

_Originally posted by @retorquere in https://github.com/retorquere/zotero-folder-import/issues/31#issuecomment-1477206166_

**Comment by retorquere** [comment]
Did you mean to ask this at the Zotfile project?
