### ISSUE TITLE
Add usage instructions to README

### ISSUE THREAD

**Issue by fredcallaway** [retorquere/zotero-folder-import#8]
I have installed the plugin but I can't figure out how to use it (nothing in the menu bar). Can you add some quick instructions to the README?

I installed 0.0.1.5

**Comment by retorquere** [comment]
Added to the readme

**Comment by retorquere** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 0.0.1.27](https://github.com/retorquere/zotero-folder-import/releases/download/builds/zotero-folder-import-0.0.1.27.xpi) ("Fixes #8")

Install in Zotero by downloading [test build 0.0.1.27](https://github.com/retorquere/zotero-folder-import/releases/download/builds/zotero-folder-import-0.0.1.27.xpi), opening the Zotero "Tools" menu, selecting "Add-ons", open the gear menu in the top right, and select "Install Add-on From File...".
