### ISSUE TITLE
Avoid Duplication

### ISSUE THREAD

**Issue by carvalhar** [retorquere/zotero-folder-import#9]
Hi,
I have a folder full of pdf and this plugin had some bugs that closed Zotero, so when i try once again it starts to reate dupliates. Is it possible to check for duplication before copying?

**Comment by retorquere** [comment]
This plugin had some bugs that closed Zotero? Can you elaborate on that?

I'm not sure how I would check on duplication. Perhaps file name and size, but a content check is going to be massively slow.

**Comment by carvalhar** [comment]
it just closed zotero after a while working on a folder very big (and very slowly).

**Comment by retorquere** [comment]
That's a bit quick to decide that this plugin had errors vs that it triggered a bug in Zotero. How many files were you importing, approximately?

**Comment by retorquere** [comment]
I have an idea how to avoid the duplicates, but it will be the weekend before I can make progress.
